spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ${SPRING_APPLICATION_NAME:hello-world}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/app}
    username: ${SPRING_DATASOURCE_USERNAME:app}
    password: ${SPRING_DATASOURCE_PASSWORD:app}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    open-in-view: false

server:
  port: ${SERVER_PORT:8088}

management:
  endpoints:
    web:
      exposure:
        include: health,info
